<?php

namespace App;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use App\Product;
use Illuminate\Support\Str;

class Booking extends Model
{

    public function Product()
    {
        return $this->belongsTo(Product::class);
    }

    public function review()
    {
        return $this->hasOne(Review::class);
    }

    public function scopeBetweenDates(Builder $query , $from , $to){
        return $query->Where('to' , '>=' , $from)->where('from' , '<=' , $to);
    }

    public static function findByReviewKey($reviewKey): ?Booking{
        return static::where('review_key' , $reviewKey)->with('product')->get()->first();
    }

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function ($booking){
            $booking->review_key = Str::uuid();
        });
    }
}
